"""
文本清洗和法律专项处理模块
包含：去页码、水印、空行、乱码、敏感信息脱敏、法律术语统一等
"""
import re
import logging
from typing import List, Dict, Tuple

logger = logging.getLogger(__name__)


class TextCleaner:
    """文本清洗器"""
    
    def __init__(self):
        self.page_patterns = [
            r'第\s*\d+\s*页',
            r'\d+\s*/\s*\d+',
            r'-\s*\d+\s*-',
            r'—\s*\d+\s*—',
            r'页\s*码\s*[:：]?\s*\d+',
        ]
        
        self.watermark_patterns = [
            r'仅供.*?参考',
            r'内部资料',
            r'机密文件',
            r'版权所有.*?保留',
            r'本文.*?下载',
            r'Document generated by',
            r'Created with',
        ]
        
        self.sensitive_patterns = {
            'id_card': (r'\d{6}(?:19|20)\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])\d{3}[\dXx]', '身份证号'),
            'phone': (r'1[3-9]\d{9}', '手机号'),
            'bank_card': (r'\d{16,19}', '银行卡号'),
        }
        
        self.law_term_mappings = {
            '民诉法': '民事诉讼法',
            '刑诉法': '刑事诉讼法',
            '行政诉讼法': '行政诉讼法',
            '民法典': '中华人民共和国民法典',
            '合同法': '中华人民共和国合同法',
            '公司法': '中华人民共和国公司法',
            '劳动法': '中华人民共和国劳动法',
        }
        
        self.redundant_patterns = [
            r'\s+',
            r'\n{3,}',
            r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]',
            r'[\ufeff\u200b\u200c\u200d]',
        ]
    
    def clean(self, text: str) -> str:
        """执行完整清洗流程"""
        if not text:
            return ""
        
        text = self.remove_page_numbers(text)
        text = self.remove_watermarks(text)
        text = self.remove_empty_lines(text)
        text = self.remove_garbled_chars(text)
        text = self.fix_broken_sentences(text)
        text = self.remove_redundant_spaces(text)
        
        return text.strip()
    
    def remove_page_numbers(self, text: str) -> str:
        """移除页码"""
        for pattern in self.page_patterns:
            text = re.sub(pattern, '', text, flags=re.IGNORECASE)
        return text
    
    def remove_watermarks(self, text: str) -> str:
        """移除水印"""
        for pattern in self.watermark_patterns:
            text = re.sub(pattern, '', text, flags=re.IGNORECASE)
        return text
    
    def remove_empty_lines(self, text: str) -> str:
        """移除多余空行"""
        text = re.sub(r'\n{3,}', '\n\n', text)
        lines = text.split('\n')
        return '\n'.join(line for line in lines if line.strip())
    
    def remove_garbled_chars(self, text: str) -> str:
        """移除乱码字符"""
        for pattern in self.redundant_patterns[2:]:
            text = re.sub(pattern, '', text)
        return text
    
    def fix_broken_sentences(self, text: str) -> str:
        """修复断行碎句"""
        lines = text.split('\n')
        fixed_lines = []
        
        for i, line in enumerate(lines):
            if not line.strip():
                fixed_lines.append(line)
                continue
            
            if i > 0 and fixed_lines:
                prev_line = fixed_lines[-1]
                if prev_line and not prev_line.endswith(('。', '；', '！', '？', '：', '.', '!', '?', '"', '」', '』')):
                    if not line.startswith(('第', '一', '二', '三', '四', '五', '六', '七', '八', '九', '十', '（', '【')):
                        fixed_lines[-1] = prev_line + line
                        continue
            
            fixed_lines.append(line)
        
        return '\n'.join(fixed_lines)
    
    def remove_redundant_spaces(self, text: str) -> str:
        """移除多余空格"""
        text = re.sub(r'[ \t]+', ' ', text)
        text = re.sub(r' \n', '\n', text)
        text = re.sub(r'\n ', '\n', text)
        return text


class LegalTextProcessor:
    """法律文本专项处理器"""
    
    def __init__(self):
        self.cleaner = TextCleaner()
        
        self.name_patterns = [
            (r'原告[：:]\s*([^\s，。；]+)', '原告'),
            (r'被告[：:]\s*([^\s，。；]+)', '被告'),
            (r'上诉人[：:]\s*([^\s，。；]+)', '上诉人'),
            (r'被上诉人[：:]\s*([^\s，。；]+)', '被上诉人'),
            (r'申请人[：:]\s*([^\s，。；]+)', '申请人'),
            (r'被申请人[：:]\s*([^\s，。；]+)', '被申请人'),
        ]
        
        self.term_standardizations = {
            '民诉法': '《中华人民共和国民事诉讼法》',
            '刑诉法': '《中华人民共和国刑事诉讼法》',
            '行政诉讼法': '《中华人民共和国行政诉讼法》',
            '民法典': '《中华人民共和国民法典》',
            '合同法': '《中华人民共和国合同法》',
            '公司法': '《中华人民共和国公司法》',
            '劳动法': '《中华人民共和国劳动法》',
            '刑法': '《中华人民共和国刑法》',
            '宪法': '《中华人民共和国宪法》',
        }
    
    def process(self, text: str, desensitize: bool = True) -> Tuple[str, Dict]:
        """处理法律文本"""
        info = {}
        
        text = self.cleaner.clean(text)
        
        if desensitize:
            text, sensitive_info = self.desensitize(text)
            info['sensitive_info'] = sensitive_info
        
        text = self.standardize_terms(text)
        
        text = self.extract_core_content(text)
        
        return text, info
    
    def desensitize(self, text: str) -> Tuple[str, Dict]:
        """脱敏敏感信息"""
        sensitive_info = {}
        
        for key, (pattern, name) in self.cleaner.sensitive_patterns.items():
            matches = re.findall(pattern, text)
            if matches:
                sensitive_info[name] = len(matches)
                text = re.sub(pattern, f'[{name}已脱敏]', text)
        
        for pattern, role in self.name_patterns:
            matches = re.findall(pattern, text)
            for match in matches:
                if len(match) >= 2:
                    text = text.replace(match, self._mask_name(match))
        
        return text, sensitive_info
    
    def _mask_name(self, name: str) -> str:
        """姓名脱敏"""
        if len(name) <= 2:
            return name[0] + '*'
        else:
            return name[0] + '*' * (len(name) - 2) + name[-1]
    
    def standardize_terms(self, text: str) -> str:
        """统一法律术语"""
        for short, full in self.term_standardizations.items():
            pattern = r'(?<!《)' + re.escape(short) + r'(?!》)'
            text = re.sub(pattern, full, text)
        
        return text
    
    def extract_core_content(self, text: str) -> str:
        """提取核心语义内容"""
        core_sections = []
        
        article_pattern = r'第[一二三四五六七八九十百零]+条[^第]*'
        articles = re.findall(article_pattern, text)
        if articles:
            core_sections.extend(articles)
        
        key_patterns = [
            r'裁判要旨[：:][^。\n]+[。\n]',
            r'本院认为[：:][^。\n]+[。\n]',
            r'判决如下[：:][^。\n]+[。\n]',
            r'裁定如下[：:][^。\n]+[。\n]',
        ]
        
        for pattern in key_patterns:
            matches = re.findall(pattern, text)
            core_sections.extend(matches)
        
        return text
    
    def remove_redundant_content(self, text: str) -> str:
        """剔除无关冗余表述"""
        redundant_patterns = [
            r'本件与原件核对无异',
            r'审判长[^\n]+',
            r'书记员[^\n]+',
            r'（此页无正文）',
            r'附：相关法律条文',
        ]
        
        for pattern in redundant_patterns:
            text = re.sub(pattern, '', text)
        
        return text
